services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ctrxok
      MONGO_INITDB_ROOT_PASSWORD: qsrhoFRf6RMnGs7d
    volumes:
      - ./db_data/:/data/db/
